language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
arch: amd64
os: linux
dist: bionic
# command to install dependencies
install:
  - sudo apt-get install tesseract-ocr
  - pip install -r requirements.txt
# command to run tests
script:
  - python test.py